spring:
  profiles:
    active: dev,kubernetes
replicas: 1
containerPort: 8888
discovery:
  enabled: true
ingress:
  enabled: false
appName: cloud-config-server
image:
  repository: "194205500841.dkr.ecr.us-east-2.amazonaws.com/cloud-config-server"
  tag: "4eefbc4"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 75
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 300m
    memory: 512Mi