spring:
  profiles:
    active: dev,kubernetes
namespace: terraform-trocks-namespace
replicas: 1
discovery:
  enabled: false
ingress:
  enabled: false
# appName: generic-service
# image:
#   repository: placeholder-repo/generic-service
#   tag: latest